// Generated by scripts/build-plugin.js. Do not edit directly.

(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.CemSExporter = api;
}(typeof globalThis === 'undefined' ? this : globalThis, function () {
  const AXES = ['X', 'Y', 'Z'];
  const EMPTY_FACE = 'vec4(0.0)';

  function assertVec3(value, label) {
    if (!Array.isArray(value) || value.length !== 3 || value.some((item) => !Number.isFinite(item))) {
      throw new Error(`${label} must be a vec3 of finite numbers`);
    }
  }

  function formatNumber(value) {
    return Number(value).toFixed(1);
  }

  function formatVec3(value) {
    return `vec3(${value.map(formatNumber).join(', ')})`;
  }

  function formatVec4(value) {
    return `vec4(${value.map(formatNumber).join(', ')})`;
  }

  function validateModel(model) {
    if (!model || typeof model.name !== 'string' || !model.name.trim()) throw new Error('model name is required');
    if (!Array.isArray(model.parts)) throw new Error('parts must be an array');
    model.parts.forEach((part, index) => {
      if (!part || part.type !== 'cube') throw new Error(`part ${index}: unsupported part type`);
      assertVec3(part.origin, `part ${index} origin`);
      assertVec3(part.size, `part ${index} size`);
      if (part.rotation) assertVec3(part.rotation, `part ${index} rotation`);
      if (part.pivot) assertVec3(part.pivot, `part ${index} pivot`);
      if (part.faces && (!Array.isArray(part.faces) || part.faces.some((face) => !Array.isArray(face) || face.length !== 4 || face.some((item) => !Number.isFinite(item))))) {
        throw new Error(`part ${index} faces must contain vec4 values`);
      }
    });
  }

  function emitRotation(rotation) {
    return rotation
      .map((angle, index) => angle === 0 ? null : `Rotate3(radians(${formatNumber(angle)}), ${AXES[index]})`)
      .filter(Boolean)
      .join(' * ') || 'mat3(1.0)';
  }

  function emitPart(part) {
    const faces = Array.from({length: 6}, (_, index) => part.faces && part.faces[index] ? formatVec4(part.faces[index]) : EMPTY_FACE).join(', ');
    if (!part.rotation || part.rotation.every((angle) => angle === 0)) {
      return `    ADD_BOX(${formatVec3(part.origin)}, ${formatVec3(part.size)}, ${faces})`;
    }
    const pivot = part.pivot || part.origin;
    return `    ADD_BOX_ROTATE(${formatVec3(part.origin)}, ${formatVec3(part.size)}, ${emitRotation(part.rotation)}, ${formatVec3(pivot)}, ${faces})`;
  }

  function exportModel(model, modelId = 1) {
    validateModel(model);
    if (!Number.isInteger(modelId) || modelId < 0) throw new Error('model ID must be a non-negative integer');
    const glsl = [
      `// Generated by CEM-S Studio for ${model.name}.`,
      `case ${modelId}:`,
      '{',
      '    modelSize /= 8.0;',
      ...model.parts.map(emitPart),
      '}',
      'break;'
    ].join('\n');
    return {glsl, manifest: {format: 'cem-s-studio/1', model: model.name, target: 'cem-s/1.21.6'}};
  }

  return {exportModel, formatVec3, validateModel};
}));


(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.CemSBlockbenchAdapter = api;
}(typeof globalThis === 'undefined' ? this : globalThis, function () {
function vec3(value, fallback) {
  return Array.isArray(value) && value.length === 3 ? value.slice() : fallback.slice();
}

function assertNoRotatedParent(cube) {
  let parent = cube.parent;
  while (parent) {
    if (Array.isArray(parent.rotation) && parent.rotation.some((angle) => angle !== 0)) {
      throw new Error(`cube "${cube.name || 'unnamed'}" is inside rotated group "${parent.name || 'unnamed'}"; bake the group rotation before export`);
    }
    parent = parent.parent;
  }
}

function assertSingleAxisRotation(cube) {
  const activeAxes = vec3(cube.rotation, [0, 0, 0]).filter((angle) => angle !== 0);
  if (activeAxes.length > 1) throw new Error(`cube "${cube.name || 'unnamed'}" has multi-axis rotation; use one axis until Euler order support is added`);
}

function toCemPart(cube, index) {
  assertNoRotatedParent(cube);
  assertSingleAxisRotation(cube);
  const from = vec3(cube.from, [0, 0, 0]);
  const to = vec3(cube.to, [0, 0, 0]);
  const faceOrder = ['down', 'up', 'north', 'east', 'south', 'west'];
  const faces = faceOrder.map((side) => {
    const face = cube.faces && cube.faces[side];
    if (face && face.enabled === false) throw new Error(`cube "${cube.name || 'unnamed'}" has disabled face "${side}"; disabled faces are not supported`);
    if (face && face.rotation && face.rotation % 360 !== 0) throw new Error(`cube "${cube.name || 'unnamed'}" has rotated face "${side}"; rotate UVs manually before export`);
    const uv = face && face.uv;
    return uv && [uv[0], uv[1], uv[2] - uv[0], uv[3] - uv[1]];
  });
  const part = {
    name: cube.name || `cube_${index + 1}`,
    type: 'cube',
    origin: to.map((value, axis) => (value + from[axis]) / 2),
    size: to.map((value, axis) => (value - from[axis]) / 2),
    // CEM-S's ADD_BOX_ROTATE subtracts rotPivot after applying Rotation;
    // negating Blockbench's pivot yields the standard rotate-around-pivot transform.
    pivot: vec3(cube.origin, from).map((value) => value === 0 ? 0 : -value),
    rotation: vec3(cube.rotation, [0, 0, 0])
  };
  if (faces.some(Boolean)) part.faces = faces;
  return part;
}

function toCemModel(name, cubes) {
  if (!Array.isArray(cubes)) throw new Error('cubes must be an array');
  return {name: name || 'cem_model', parts: cubes.map(toCemPart)};
}

return {toCemModel};
}));


(function () {
  const {exportModel} = CemSExporter;
  const {toCemModel} = CemSBlockbenchAdapter;
  let exportAction;

  function exportCurrentProject() {
    const cubes = Cube.all || [];
    if (!cubes.length) {
      Blockbench.showQuickMessage('CEM-S Studio: add at least one cube before exporting.');
      return;
    }

    try {
      const modelName = Project.name || 'cem_model';
      const value = window.prompt('CEM-S model ID (must match the detection file)', '1');
      if (value === null) return;
      const modelId = Number(value);
      const exported = exportModel(toCemModel(modelName, cubes), modelId);
      Blockbench.export({
    resource_id: 'cem_s_studio_glsl',
        type: 'CEM-S 1.21.6 model',
        extensions: ['glsl'],
        name: modelName
      }, (path) => {
        if (!path) return;
        Blockbench.writeFile(path, {content: exported.glsl});
        Blockbench.showQuickMessage('CEM-S Studio: GLSL model exported.');
      });
    } catch (error) {
      Blockbench.showMessageBox({title: 'CEM-S Studio export failed', message: error.message});
    }
  }

  Plugin.register('cem_s_studio', {
    title: 'CEM-S Studio',
    author: 'CEM-S Studio contributors',
    description: 'Exports Blockbench cubes to CEM-S 1.21.6 GLSL.',
    icon: 'extension',
    version: '0.1.0',
    min_version: '4.12.0',
    variant: 'desktop',
    onload() {
      exportAction = new Action('export_cem_s_forge', {name: 'Export CEM-S 1.21.6 Model', icon: 'save', click: exportCurrentProject});
      MenuBar.addAction(exportAction, 'file.export');
    },
    onunload() {
      if (exportAction) exportAction.delete();
    }
  });
}());
