const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const sources = ['src/cem-exporter.js', 'src/blockbench-adapter.js', 'src/plugin-entry.js'];
const output = ['// Generated by scripts/build-plugin.js. Do not edit directly.', ...sources.map((file) => fs.readFileSync(path.join(root, file), 'utf8'))].join('\n\n');
fs.writeFileSync(path.join(root, 'cem_s_studio.js'), output);
