const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const sources = ['src/cem-exporter.js', 'src/blockbench-adapter.js', 'src/cemst.js', 'src/pack-builder.js'];
const {SOURCES} = require(path.join(root, 'src', 'cem-runtime.js'));
const runtimeFiles = Object.fromEntries(Object.keys(SOURCES).map((destination) => {
  const source = path.join(root, 'vendor', 'cem-s', destination);
  if (!fs.existsSync(source)) throw new Error(`Missing bundled CEM-S runtime file: ${destination}`);
  return [destination, fs.readFileSync(source, 'utf8')];
}));
const runtimeBundle = `(function (root) { root.CemSBundledRuntime = Object.freeze(${JSON.stringify(runtimeFiles)}); }(typeof globalThis === 'undefined' ? this : globalThis));`;
const tailSources = ['src/cem-runtime.js', 'src/plugin-entry.js'];
const output = ['// Generated by scripts/build-plugin.js. Do not edit directly.', ...sources.map((file) => fs.readFileSync(path.join(root, file), 'utf8')), runtimeBundle, ...tailSources.map((file) => fs.readFileSync(path.join(root, file), 'utf8'))].join('\n\n');
fs.writeFileSync(path.join(root, 'cem_s_studio.js'), output);
