(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.CemSPackBuilder = api;
}(typeof globalThis === 'undefined' ? this : globalThis, function () {
  function slugify(value) {
    return String(value || 'model').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'model';
  }

  function json(value) {
    return JSON.stringify(value, null, 2) + '\n';
  }

  function managedImport(id, path) {
    return `// CEM-S Studio BEGIN ${id}\n#moj_import <${path}>\n// CEM-S Studio END ${id}`;
  }

  function upsertManagedSection(source, id, content) {
    const begin = `// CEM-S Studio BEGIN ${id}`;
    const end = `// CEM-S Studio END ${id}`;
    const section = `${begin}\n${content}\n${end}`;
    const pattern = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
    return pattern.test(source) ? source.replace(pattern, section) : `${source.replace(/[\\s\\n]*$/, '')}\n${section}\n`;
  }

  function detectionSource(project) {
    const detection = project.project.detection;
    const color = detection.color.join(', ');
    const [x, y] = detection.pixel;
    const setup = [
      `cem = ${project.project.modelId};`,
      `cem_reverse = ${detection.reverse ? 1 : 0};`,
      detection.corner === 'yx' ? 'corner = corners[(gl_VertexID) % 4].yx;' : null,
      `cem_size = ${detection.size};`
    ].filter(Boolean).map(line => `        ${line}`).join('\n');
    const marker = `round(texelFetch(Sampler0, ivec2(${x}, ${y}), 0) * 255) == vec4(${color})`;
    if (detection.face.mode === 'all') {
      return `// Generated by CEM-S Studio.\nif (${marker})\n{\n${setup.replace(/^ {8}/gm, '    ')}\n}`;
    }
    const unmatched = detection.hideUnmatched ? '\n    else\n    {\n        gl_Position = vec4(0);\n    }' : '';
    return `// Generated by CEM-S Studio.\nif (${marker})\n{\n    if (gl_VertexID / 4 % ${detection.face.count} == ${detection.face.index})\n    {\n${setup}\n    }${unmatched}\n}`;
  }

  function buildPackFiles(document, modelGlsl, options = {}) {
    const project = document.project;
    const id = slugify(project.name);
    const modelPath = `cem_user/models/${project.targetType}/${id}.glsl`;
    const detectionPath = `cem_user/detection/${project.targetType}/${id}.glsl`;
    const generated = {
      'pack.mcmeta': json({pack: {pack_format: project.resourcePack.packFormat, description: project.resourcePack.description}}),
      'assets/minecraft/shaders/include/cem_user/models.glsl': managedImport(project.modelId, modelPath),
      [`assets/minecraft/shaders/include/${modelPath}`]: modelGlsl.endsWith('\n') ? modelGlsl : `${modelGlsl}\n`,
      'assets/minecraft/shaders/include/cem_user/detection.glsl': managedImport(project.modelId, detectionPath),
      [`assets/minecraft/shaders/include/${detectionPath}`]: detectionSource(document),
      'cem-studio/project.json': json(document),
      'cem-studio/README.txt': 'Generated by CEM-S Studio. Keep the CEM-S Studio managed sections when updating this pack.\n'
    };
    return Object.assign({}, options.runtimeFiles || {}, generated);
  }

  function mergePackFiles(existing, generated, project) {
    const result = Object.assign({}, existing);
    const id = project.project.modelId;
    const modelsPath = 'assets/minecraft/shaders/include/cem_user/models.glsl';
    const detectionPath = 'assets/minecraft/shaders/include/cem_user/detection.glsl';
    for (const [filePath, content] of Object.entries(generated)) {
      if (filePath === 'pack.mcmeta') {
        if (!result[filePath]) result[filePath] = content;
      } else if (filePath === modelsPath || filePath === detectionPath) {
        const sectionPattern = new RegExp(`^// CEM-S Studio BEGIN ${id}\\n([\\s\\S]*?)\\n// CEM-S Studio END ${id}\\s*$`, 'm');
        const sectionContent = content.replace(sectionPattern, '$1');
        result[filePath] = upsertManagedSection(result[filePath] || '', id, sectionContent);
      } else {
        result[filePath] = content;
      }
    }
    return result;
  }

  return {slugify, buildPackFiles, mergePackFiles, upsertManagedSection};
}));
