(function (root, factory) {
  const api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  root.CemSPackBuilder = api;
}(typeof globalThis === 'undefined' ? this : globalThis, function () {
  function slugify(value) {
    return String(value || 'model').trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'model';
  }

  function json(value) {
    return JSON.stringify(value, null, 2) + '\n';
  }

  function managedImport(id, path) {
    return `// CEM-S Studio BEGIN ${id}\n#moj_import <${path}>\n// CEM-S Studio END ${id}`;
  }

  function upsertManagedSection(source, id, content) {
    const begin = `// CEM-S Studio BEGIN ${id}`;
    const end = `// CEM-S Studio END ${id}`;
    const section = `${begin}\n${content}\n${end}`;
    const pattern = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
    return pattern.test(source) ? source.replace(pattern, section) : `${source.replace(/[\\s\\n]*$/, '')}\n${section}\n`;
  }

  function detectionSource(project, baseTextureSize = null) {
    const detection = project.project.detection;
    const color = detection.color.join(', ');
    const [x, y] = detection.pixel;
    const marker = `round(texelFetch(Sampler0, ivec2(${x}, ${y}), 0) * 255) == vec4(${color})`;
    const matchSource = match => {
      if (match.mode === 'all') return 'true';
      if (match.mode === 'vertex_id') return `gl_VertexID / 4 % ${match.count} == ${match.index}`;
      const cornerIndex = `(gl_VertexID + ${match.cornerOffset}) % 4`;
      return `uv - ${match.cornerSet}[${cornerIndex}] * vec2(${match.scale.join(', ')}) == vec2(${match.offset.join(', ')})`;
    };
    const textureSetup = baseTextureSize
      ? `\n    uv = floor(UV0 * vec2(${baseTextureSize.join(', ')}));\n    texCoord0 = UV0 * vec2(${baseTextureSize.join(', ')}) / vec2(textureSize(Sampler0, 0));`
      : '';
    const branches = detection.branches.map((branch, index) => {
      const setup = [
        `cem = ${project.project.modelId + branch.modelIdOffset};`,
        `cem_reverse = ${branch.reverse ? 1 : 0};`,
        `cem_keep_original = ${detection.matchedFaceMode === 'overlay' ? 1 : 0};`,
        branch.corner === 'yx' ? 'corner = corners[(gl_VertexID) % 4].yx;' : null,
        `cem_size = ${branch.size};`
      ].filter(Boolean).map(line => `        ${line}`).join('\n');
      return `    ${index ? 'else if' : 'if'} (${matchSource(branch.match)})\n    {\n${setup}\n    }`;
    }).join('\n');
    const unmatched = detection.hideUnmatched ? '\n    else\n    {\n        gl_Position = vec4(0);\n    }' : '';
    return `// Generated by CEM-S Studio.\nif (${marker})\n{${textureSetup}\n${branches}${unmatched}\n}`;
  }

  function textureFilePaths(textureFile) {
    const paths = [textureFile?.path, ...(Array.isArray(textureFile?.paths) ? textureFile.paths : [])].filter(Boolean);
    return [...new Set(paths)];
  }

  function buildPackFiles(document, modelGlsl, options = {}) {
    const project = document.project;
    const id = slugify(project.name);
    const modelPath = `cem_user/models/${project.targetType}/${id}.glsl`;
    const detectionPath = `cem_user/detection/${project.targetType}/${id}.glsl`;
    const pack = {pack_format: project.resourcePack.packFormat, description: project.resourcePack.description};
    if (project.resourcePack.packFormat >= 75) {
      pack.min_format = project.resourcePack.packFormat;
      pack.max_format = project.resourcePack.packFormat;
    }
    const generated = {
      'pack.mcmeta': json({pack}),
      'assets/minecraft/shaders/include/cem_user/models.glsl': managedImport(project.modelId, modelPath),
      [`assets/minecraft/shaders/include/${modelPath}`]: modelGlsl.endsWith('\n') ? modelGlsl : `${modelGlsl}\n`,
      'assets/minecraft/shaders/include/cem_user/detection.glsl': managedImport(project.modelId, detectionPath),
      [`assets/minecraft/shaders/include/${detectionPath}`]: detectionSource(document, options.textureFile?.baseSize || null),
      'cem-studio/project.json': json(document),
      'cem-studio/README.txt': 'Generated by CEM-S Studio. Keep the CEM-S Studio managed sections when updating this pack.\n'
    };
    if (options.textureFile) {
      const paths = textureFilePaths(options.textureFile);
      if (!paths.length || paths.some(path => typeof path !== 'string' || !path.startsWith('assets/') || !path.endsWith('.png'))) throw new Error('textureFile paths must be assets PNG paths');
      if (!(options.textureFile.content instanceof Uint8Array)) throw new Error('textureFile.content must be PNG bytes');
      if (!Array.isArray(options.textureFile.baseSize) || options.textureFile.baseSize.length !== 2 || options.textureFile.baseSize.some(value => !Number.isInteger(value) || value <= 0)) throw new Error('textureFile.baseSize must be a positive ivec2');
      for (const path of paths) generated[path] = options.textureFile.content;
      generated[`cem-studio/texture-mappings/${id}.json`] = json({model: project.name, targetEntity: project.targetEntity, baseSize: options.textureFile.baseSize, paths});
    }
    return Object.assign({}, options.runtimeFiles || {}, generated);
  }

  function buildWorkspacePackFiles(document, modelGlslById, options = {}) {
    const models = document?.workspace?.models;
    if (!Array.isArray(models) || !models.length) throw new Error('workspace must contain at least one model');
    const versions = new Set();
    const packFormats = new Set();
    const modelIds = new Set();
    const outputPaths = new Set();
    const generated = Object.assign({}, options.runtimeFiles || {});
    const modelsAggregator = 'assets/minecraft/shaders/include/cem_user/models.glsl';
    const detectionAggregator = 'assets/minecraft/shaders/include/cem_user/detection.glsl';
    let modelImports = '';
    let detectionImports = '';
    let packMeta = null;
    const addFile = (filePath, content) => {
      if (Object.prototype.hasOwnProperty.call(generated, filePath)) {
        const previous = generated[filePath];
        const equal = previous instanceof Uint8Array && content instanceof Uint8Array
          ? previous.length === content.length && previous.every((value, index) => value === content[index])
          : previous === content;
        if (!equal) throw new Error(`workspace output path conflict: ${filePath}`);
        return;
      }
      generated[filePath] = content;
    };
    for (const model of models) {
      if (!model || !model.project || typeof model.id !== 'string') throw new Error('workspace model entries must contain id and project');
      if (modelIds.has(model.project.modelId)) throw new Error(`duplicate workspace modelId: ${model.project.modelId}`);
      modelIds.add(model.project.modelId);
      versions.add(model.project.cemVersion);
      packFormats.add(model.project.resourcePack?.packFormat);
      const slug = slugify(model.project.name);
      const outputKey = `${model.project.targetType}/${slug}`;
      if (outputPaths.has(outputKey)) throw new Error(`workspace output path conflict: ${outputKey}`);
      outputPaths.add(outputKey);
      if (!modelGlslById || typeof modelGlslById[model.id] !== 'string') throw new Error(`missing GLSL for workspace model: ${model.id}`);
      const child = buildPackFiles({project: model.project, blockbench: model.blockbench || {}}, modelGlslById[model.id], {textureFile: options.textureFiles?.[model.id]});
      if (!packMeta) packMeta = child['pack.mcmeta'];
      const modelPattern = new RegExp(`^// CEM-S Studio BEGIN ${model.project.modelId}\\n([\\s\\S]*?)\\n// CEM-S Studio END ${model.project.modelId}\\s*$`, 'm');
      const modelSection = child[modelsAggregator]?.match(modelPattern)?.[1];
      const detectionSection = child[detectionAggregator]?.match(modelPattern)?.[1];
      if (!modelSection || !detectionSection) throw new Error(`workspace aggregator section missing: ${model.id}`);
      modelImports = upsertManagedSection(modelImports, model.project.modelId, modelSection);
      detectionImports = upsertManagedSection(detectionImports, model.project.modelId, detectionSection);
      for (const [filePath, content] of Object.entries(child)) {
        if (["pack.mcmeta", modelsAggregator, detectionAggregator, 'cem-studio/project.json', 'cem-studio/README.txt'].includes(filePath)) continue;
        addFile(filePath, content);
      }
      addFile(`cem-studio/models/${model.id}.json`, json({format: 'cemst', formatVersion: 2, project: model.project, blockbench: model.blockbench || {}}));
    }
    if (versions.size !== 1 || packFormats.size !== 1) throw new Error('workspace models must target the same Minecraft runtime');
    generated['pack.mcmeta'] = packMeta;
    generated[modelsAggregator] = modelImports;
    generated[detectionAggregator] = detectionImports;
    generated['cem-studio/workspace.json'] = json({format: document.format || 'cemst', formatVersion: document.formatVersion || 3, workspace: {version: document.workspace.version, activeModel: document.workspace.activeModel, models: models.map(model => ({id: model.id, name: model.project.name, modelId: model.project.modelId, cemVersion: model.project.cemVersion, targetType: model.project.targetType}))}});
    generated['cem-studio/README.txt'] = 'Generated by CEM-S Studio. Keep the CEM-S Studio managed sections when updating this pack.\n';
    return generated;
  }

  function mergePackFiles(existing, generated, project) {
    const result = Object.assign({}, existing);
    const id = project.project.modelId;
    const modelsPath = 'assets/minecraft/shaders/include/cem_user/models.glsl';
    const detectionPath = 'assets/minecraft/shaders/include/cem_user/detection.glsl';
    for (const [filePath, content] of Object.entries(generated)) {
      if (filePath === 'pack.mcmeta') {
        if (!result[filePath]) result[filePath] = content;
      } else if (filePath === modelsPath || filePath === detectionPath) {
        const sectionPattern = new RegExp(`^// CEM-S Studio BEGIN ${id}\\n([\\s\\S]*?)\\n// CEM-S Studio END ${id}\\s*$`, 'm');
        const sectionContent = content.replace(sectionPattern, '$1');
        result[filePath] = upsertManagedSection(result[filePath] || '', id, sectionContent);
      } else {
        result[filePath] = content;
      }
    }
    return result;
  }

  return {slugify, buildPackFiles, buildWorkspacePackFiles, mergePackFiles, upsertManagedSection, detectionSource, textureFilePaths};
}));
